package com.old.silence.data.mybatis.test;

import com.baomidou.mybatisplus.core.metadata.TableFieldInfo;
import com.baomidou.mybatisplus.core.metadata.TableInfo;
import com.baomidou.mybatisplus.core.metadata.TableInfoHelper;
import com.old.silence.core.test.data.RandomData;
import org.springframework.beans.BeanUtils;
import org.springframework.beans.BeanWrapper;
import org.springframework.beans.PropertyAccessorFactory;

import javax.sql.DataSource;
import java.beans.PropertyDescriptor;
import java.util.Set;
import java.util.stream.Stream;

/**
 * Factory for creating mock entities for testing
 * Adapted for MyBatis Plus
 * 
 * @author moryzang
 */
class EntityMockFactory<T, ID> {

    private static final Set<String> AUDITABLE_PROPERTIES = Set.of(
            "createBy", "createDate", "updateBy", "updateDate"
    );

    private final DataSource dataSource;
    private final Class<T> entityType;
    private final TableInfo tableInfo;

    public EntityMockFactory(DataSource dataSource, Class<T> entityType) {
        this.dataSource = dataSource;
        this.entityType = entityType;
        this.tableInfo = TableInfoHelper.getTableInfo(entityType);
        if (this.tableInfo == null) {
            throw new IllegalArgumentException("No TableInfo found for entity type: " + entityType);
        }
    }

    /**
     * Create mock entity for insert operation
     * Auto-increment ID will not be set (will be generated by database)
     * 
     * @param customizer optional customizer for additional modifications
     * @return mock entity instance
     */
    T mockForInsert(MockedEntityCustomizer<T> customizer) {
        T entity = BeanUtils.instantiateClass(entityType);
        BeanWrapper wrapper = PropertyAccessorFactory.forBeanPropertyAccess(entity);

        // Set values for all insertable fields
        for (TableFieldInfo fieldInfo : tableInfo.getFieldList()) {
            // Skip non-insertable fields (check if insert allowed)
            // MyBatis Plus: insertable fields don't have a dedicated flag like Spring Data
            // We assume all fields are insertable unless specified otherwise in annotations

            // Skip auditable fields (will be filled by auditing)
            if (AUDITABLE_PROPERTIES.contains(fieldInfo.getProperty())) {
                continue;
            }

            // Generate and set value
            Object value = generateValue(fieldInfo);
            if (value != null) {
                wrapper.setPropertyValue(fieldInfo.getProperty(), value);
            }
        }

        // Primary key handling:
        // - For AUTO increment: don't set, let database generate
        // - For other types: MyBatis Plus will handle it
        // Note: After insert, MyBatis Plus will auto-fill the ID back to the entity

        if (customizer != null) {
            customizer.customize(entity);
        }

        return entity;
    }

    /**
     * Create mock entity for update operation
     * 
     * @param id entity ID
     * @param customizer optional customizer for additional modifications
     * @return mock entity instance with ID set
     */
    T mockForUpdate(ID id, MockedEntityCustomizer<T> customizer) {
        T entity = BeanUtils.instantiateClass(entityType);
        BeanWrapper wrapper = PropertyAccessorFactory.forBeanPropertyAccess(entity);

        // Set primary key
        wrapper.setPropertyValue(tableInfo.getKeyProperty(), id);

        // Set values for all updatable fields
        for (TableFieldInfo fieldInfo : tableInfo.getFieldList()) {
            // MyBatis Plus: updatable fields don't have a dedicated flag
            // We assume all fields are updatable unless specified otherwise

            // Skip auditable fields
            if (AUDITABLE_PROPERTIES.contains(fieldInfo.getProperty())) {
                continue;
            }

            // Generate and set value
            Object value = generateValue(fieldInfo);
            if (value != null) {
                wrapper.setPropertyValue(fieldInfo.getProperty(), value);
            }
        }

        if (customizer != null) {
            customizer.customize(entity);
        }

        return entity;
    }

    /**
     * Create mock DTO for update operation
     * Only properties present in DTO type will be set
     * 
     * @param id entity ID
     * @param dtoType DTO class type
     * @param customizer optional customizer for additional modifications
     * @param <DTO> DTO type
     * @return mock DTO instance
     */
    <DTO> DTO mockDtoForUpdate(ID id, Class<DTO> dtoType, MockedEntityCustomizer<DTO> customizer) {
        DTO dto = BeanUtils.instantiateClass(dtoType);
        BeanWrapper dtoWrapper = PropertyAccessorFactory.forBeanPropertyAccess(dto);

        // Set primary key
        if (dtoWrapper.isWritableProperty(tableInfo.getKeyProperty())) {
            dtoWrapper.setPropertyValue(tableInfo.getKeyProperty(), id);
        }

        // Get DTO properties
        PropertyDescriptor[] descriptors = BeanUtils.getPropertyDescriptors(dtoType);

        for (PropertyDescriptor descriptor : descriptors) {
            if ("class".equals(descriptor.getName())) {
                continue;
            }

            String propertyName = descriptor.getName();

            // Skip ID (already set)
            if (propertyName.equals(tableInfo.getKeyProperty())) {
                continue;
            }

            // Find corresponding field in entity
            TableFieldInfo fieldInfo = tableInfo.getFieldList().stream()
                    .filter(f -> f.getProperty().equals(propertyName))
                    .findFirst()
                    .orElse(null);

            if (fieldInfo != null) {
                // Skip auditable fields
                if (AUDITABLE_PROPERTIES.contains(propertyName)) {
                    continue;
                }

                Object value = generateValue(fieldInfo);
                if (value != null) {
                    dtoWrapper.setPropertyValue(propertyName, value);
                }
            }
        }

        if (customizer != null) {
            customizer.customize(dto);
        }

        return dto;
    }

    /**
     * Generate value for a field
     */
    private Object generateValue(TableFieldInfo fieldInfo) {
        String columnName = fieldInfo.getColumn();
        String propertyName = fieldInfo.getProperty();
        Class<?> propertyType = fieldInfo.getPropertyType();

        // Get column metadata from database
        ColumnMetaData columnMetaData = ColumnMetaDataProvider.getColumnMetaData(
                dataSource, entityType, columnName
        );

        if (columnMetaData == null) {
            // If metadata not available, generate default value
            return generateDefaultValue(propertyType);
        }

        // Use PropertyValueGenerator to generate value
        return Stream.of(PropertyValueGenerator.values())
                .filter(generator -> generator.supports(propertyType))
                .findFirst()
                .map(generator -> generator.generate(propertyName, propertyType, columnMetaData))
                .orElse(generateDefaultValue(propertyType));
    }

    /**
     * Generate default value when column metadata is not available
     */
    private Object generateDefaultValue(Class<?> type) {
        if (type == String.class) {
            return RandomData.randomName("Test", 10);
        }
        if (type == Integer.class || type == int.class) {
            return RandomData.randomPositiveInt(1000);
        }
        if (type == Long.class || type == long.class) {
            return RandomData.randomPositiveLong(10000L);
        }
        if (type == Boolean.class || type == boolean.class) {
            return RandomData.randomBoolean();
        }
        // Add more types as needed
        return null;
    }
}
