package com.old.silence.data.mybatis.test.fixture.entity;

import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

/**
 * Test department entity for association projection tests.
 */
public class Department extends AbstractAutoGeneratedIdAuditable<Long> {

    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
