package com.old.silence.data.mybatis.test.fixture.entity;

import java.util.Map;

import com.baomidou.mybatisplus.annotation.TableField;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;
import com.old.silence.data.commons.handler.StringToMapHandler;

/**
 * Test department entity for association projection tests.
 */
public class Menu extends AbstractAutoGeneratedIdAuditable<Long> {

    @TableField("name")
    private String menuName;

    @TableField(typeHandler = StringToMapHandler.class)
    private Map<String, Object> meta;

    public String getMenuName() {
        return menuName;
    }

    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    public Map<String, Object> getMeta() {
        return meta;
    }

    public void setMeta(Map<String, Object> meta) {
        this.meta = meta;
    }
}
