package com.old.silence.data.mybatis.test.fixture.entity;

import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;

/**
 * Test role entity for ManyToMany join-table projection tests.
 */
public class Role extends AbstractAutoGeneratedIdAuditable<Long> {

    private String roleName;

    @ManyToOne
    @JoinColumn(name = "parent_role_id")
    private Role parentRole;

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public Role getParentRole() {
        return parentRole;
    }

    public void setParentRole(Role parentRole) {
        this.parentRole = parentRole;
    }
}
