package com.old.silence.data.mybatis.test.fixture.entity;

import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;

/**
 * Test task entity for nested interface projection tests.
 */
public class Task extends AbstractAutoGeneratedIdAuditable<Long> {

    private String taskName;

    @ManyToOne
    @JoinColumn(name = "project_id", referencedColumnName = "id")
    private Project project;

    public String getTaskName() {
        return taskName;
    }

    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }
}
