package com.old.silence.data.mybatis.test.fixture.entity;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;
import com.old.silence.data.commons.handler.GenericEnumTypeHandler;
import com.old.silence.data.mybatis.test.fixture.enmus.UserStatus;

import jakarta.persistence.OneToMany;

import java.util.List;

/**
 * Test entity for projection integration tests.
 * Role-association model: User -> UserRole -> Role via {@link #userRoles} (explicit join entity).
 * Department-association model: User -> UserDepartment -> Department via {@link #userDepartments} (explicit join entity).
 */
@TableName("t_user")
public class User extends AbstractAutoGeneratedIdAuditable<Long> {

    private String username;

    @TableField("is_enabled")
    private Boolean enabled;

    @TableField(value = "status", typeHandler = GenericEnumTypeHandler.class)
    private UserStatus status;

    @OneToMany(mappedBy = "user")
    private List<UserRole> userRoles;

    @OneToMany(mappedBy = "user")
    private List<UserDepartment> userDepartments;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public UserStatus getStatus() {
        return status;
    }

    public void setStatus(UserStatus status) {
        this.status = status;
    }

    public List<UserRole> getUserRoles() {
        return userRoles;
    }

    public void setUserRoles(List<UserRole> userRoles) {
        this.userRoles = userRoles;
    }

    public List<UserDepartment> getUserDepartments() {
        return userDepartments;
    }

    public void setUserDepartments(List<UserDepartment> userDepartments) {
        this.userDepartments = userDepartments;
    }
}
