package com.old.silence.data.commons.tenant;

import java.util.List;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

import com.baomidou.mybatisplus.core.metadata.TableInfo;
import com.baomidou.mybatisplus.core.metadata.TableInfoHelper;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditableTenantable;

/**
 * 维护需要追加租户条件的表名集合。
 *
 * @author moryzang
 */
public class TenantTableRegistry {

    private final Set<String> tenantTables = ConcurrentHashMap.newKeySet();

    public boolean isTenantTable(String tableName) {
        if (tenantTables.isEmpty()) {
            refresh();
        }
        return tenantTables.contains(tableName);
    }

    private void refresh() {
        List<TableInfo> tableInfos = TableInfoHelper.getTableInfos();
        if (tableInfos == null || tableInfos.isEmpty()) {
            return;
        }

        for (TableInfo tableInfo : tableInfos) {
            Class<?> entityType = tableInfo.getEntityType();
            if (entityType != null
                    && AbstractAutoGeneratedIdAuditableTenantable.class.isAssignableFrom(entityType)) {
                tenantTables.add(tableInfo.getTableName());
            }
        }
    }
}


