package com.old.silence.data.commons.injecter;

import org.apache.ibatis.session.Configuration;

import java.util.List;
import java.util.Set;
import java.util.function.Predicate;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.core.injector.AbstractMethod;
import com.baomidou.mybatisplus.core.injector.DefaultSqlInjector;
import com.baomidou.mybatisplus.core.metadata.TableFieldInfo;
import com.baomidou.mybatisplus.core.metadata.TableInfo;
import com.baomidou.mybatisplus.extension.injector.methods.InsertBatchSomeColumn;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditableTenantable;
import com.old.silence.data.commons.injecter.support.UpdateBatchSomeColumnById;

/**
 * @author moryzang
 */
public class CustomSqlInjector extends DefaultSqlInjector {


    @Override
    public List<AbstractMethod> getMethodList(Configuration configuration, Class<?> mapperClass, TableInfo tableInfo) {
        List<AbstractMethod> methods = super.getMethodList(configuration, mapperClass, tableInfo);

        // 批量插入
        methods.add(new InsertBatchSomeColumn("insertAll", createInsertPredicate(tableInfo)));

        // 批量更新
        methods.add(new UpdateBatchSomeColumnById("updateAll", createUpdatePredicate(tableInfo)));

        return methods;
    }

    /**
     * 创建插入字段的 Predicate
     */
    private Predicate<TableFieldInfo> createInsertPredicate(TableInfo tableInfo) {
        return field -> {
            // 基础排除条件
            if (notBaseExcludeCondition(field, tableInfo)) {
                return false;
            }

            // 插入特定排除：排除插入时填充的字段
            return field.getFieldFill() != FieldFill.INSERT && field.getFieldFill() != FieldFill.INSERT_UPDATE;
        };
    }

    /**
     * 创建更新字段的 Predicate
     */
    private Predicate<TableFieldInfo> createUpdatePredicate(TableInfo tableInfo) {
        return field -> {
            // 基础排除条件
            if (notBaseExcludeCondition(field, tableInfo)) {
                return false;
            }

            // 更新特定排除：排除更新时填充的字段和乐观锁字段
            if (field.getFieldFill() == FieldFill.UPDATE || field.getFieldFill() == FieldFill.INSERT_UPDATE) {
                return false;
            }
            return !field.getProperty().equals("version");
        };
    }

    /**
     * 基础排除条件（插入和更新共用的逻辑）
     */
    private boolean notBaseExcludeCondition(TableFieldInfo field, TableInfo tableInfo) {
        return field.isLogicDelete() || isTenantField(field, tableInfo);

    }

    /**
     * 判断是否是租户字段
     */
    private boolean isTenantField(TableFieldInfo field, TableInfo tableInfo) {
        return field.getProperty().equals("namespace_id")
                && AbstractAutoGeneratedIdAuditableTenantable.class.isAssignableFrom(tableInfo.getEntityType());
    }
}