package com.old.silence.data.commons.domain;

import java.io.Serializable;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableLogic;

/**
 * @author moryzang
 */
public abstract class AbstractAutoGeneratedIdLogicalDeletionAuditable<ID extends Serializable, DE extends Serializable>
        extends AbstractAutoGeneratedIdAuditable<ID> {

    private static final long serialVersionUID = 7222433471527594425L;

    @TableLogic
    @TableField(value = "is_deleted")
    private DE deleted;

    public DE getDeleted() {
        return deleted;
    }

    public void setDeleted(DE deleted) {
        this.deleted = deleted;
    }
}
