package com.old.silence.data.commons.domain;

import org.springframework.lang.Nullable;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.fasterxml.jackson.annotation.JsonProperty;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.Version;
import java.io.Serializable;
import java.time.Instant;
import java.util.Objects;
import java.util.Optional;


/**
 * @author MurrayZhang
 */
public abstract class AbstractAutoGeneratedIdAuditable<ID extends Serializable> implements Serializable {

    private static final long serialVersionUID = -8981379469380861749L;

    @Nullable
    @TableId(type = IdType.AUTO)
    private ID id;

    @Column(updatable = false)
    private String createdBy;

    @JsonProperty("createdAt")
    @Column(name = "CREATED_DATE", updatable = false)
    private Instant createdDate;

    @Column(name = "UPDATED_BY")
    private String lastModifiedBy;

    @Version
    @JsonProperty("lastModifiedAt")
    @Column(name = "UPDATED_DATE")
    private Instant lastModifiedDate;

    @Id
    @Nullable
    public ID getId() {
        return id;
    }

    public void setId(ID id) {
        this.id = id;
    }


    public Optional<String> getCreatedBy() {
        return Optional.ofNullable(createdBy);
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Optional<Instant> getCreatedDate() {
        return Optional.ofNullable(createdDate);
    }

    public void setCreatedDate(Instant createdDate) {
        this.createdDate = createdDate;
    }

    public Optional<String> getLastModifiedBy() {
        return Optional.ofNullable(lastModifiedBy);
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Optional<Instant> getLastModifiedDate() {
        return Optional.ofNullable(lastModifiedDate);
    }

    public void setLastModifiedDate(Instant lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    @Override
    public int hashCode() {
        int hashCode = 17;
        ID id = getId();
        hashCode += null == id ? 0 : id.hashCode() * 31;
        return hashCode;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || getClass() != obj.getClass()) {
            return false;
        }
        AbstractAutoGeneratedIdAuditable<?> other = (AbstractAutoGeneratedIdAuditable<?>) obj;
        return Objects.equals(getId(), other.getId());
    }

    @Override
    public String toString() {
        return String.format("Entity of type %s with id: %s", this.getClass().getName(), getId());
    }
}
