package com.old.silence.data.commons.domain;

import com.baomidou.mybatisplus.annotation.TableField;

import javax.persistence.Column;
import javax.persistence.MappedSuperclass;
import java.io.Serializable;

/**
 * @author murrayZhang
 */
@MappedSuperclass
public abstract class AbstractAutoGeneratedIdAuditableTenantable<ID extends Serializable, TID extends Serializable>
        extends AbstractAutoGeneratedIdAuditable<ID>  {

    private static final long serialVersionUID = -3679581344164968191L;

    @Column(updatable = false)
    @TableField("tenant_id")
    private TID tenantId;

    public TID getTenantId() {
        return tenantId;
    }

    public void setTenantId(TID tenantId) {
        this.tenantId = tenantId;
    }
}
