package com.old.silence.data.commons.domain;

import jakarta.persistence.Column;

import java.io.Serializable;

import com.baomidou.mybatisplus.annotation.TableField;

/**
 * @author murrayZhang
 */
public abstract class AbstractAutoGeneratedIdAuditableTenantable<ID extends Serializable, TID extends Serializable>
        extends AbstractAutoGeneratedIdAuditable<ID> implements Tenantable<TID> {

    private static final long serialVersionUID = -3679581344164968191L;

    @Column(updatable = false)
    @TableField("namespace_id")
    private TID namespaceId;

    @Override
    public TID getNamespaceId() {
        return namespaceId;
    }

    @Override
    public void setNamespaceId(TID namespaceId) {
        this.namespaceId = namespaceId;
    }
}
