package com.old.silence.data.commons.domain;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableLogic;

import javax.persistence.Column;
import javax.persistence.MappedSuperclass;
import java.io.Serializable;

/**
 * @author murrayZhang
 */
@MappedSuperclass
public abstract class AbstractAutoGeneratedIdLogicalDeletionAuditable<ID extends Serializable, DE extends Serializable>
        extends AbstractAutoGeneratedIdAuditable<ID> {

    private static final long serialVersionUID = 7222433471527594425L;

    @Column(insertable = false, updatable = false)
    @TableLogic
    @TableField(value = "is_deleted")
    private DE deleted;

    public DE getDeleted() {
        return deleted;
    }

    public void setDeleted(DE deleted) {
        this.deleted = deleted;
    }
}
