package com.old.silence.data.commons.handler;

import org.apache.ibatis.reflection.MetaObject;

import com.baomidou.mybatisplus.core.handlers.MetaObjectHandler;
import com.old.silence.core.security.TenantContextAware;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditableTenantable;

/**
 * 负责在插入时为多租户实体填充 namespaceId。
 *
 * <p>只有当实体继承 {@link AbstractAutoGeneratedIdAuditableTenantable} 时才进行填充。</p>
 *
 * @author moryzang
 */
public class TenantMetaObjectHandler implements MetaObjectHandler {

    private final TenantContextAware<String> tenantContextAware;

    public TenantMetaObjectHandler(TenantContextAware<String> tenantContextAware) {
        this.tenantContextAware = tenantContextAware;
    }

    @Override
    public void insertFill(MetaObject metaObject) {
        if (!supportsTenantFill(metaObject)) {
            return;
        }
        this.strictInsertFill(metaObject, "namespaceId", this::currentTenantId, String.class);
    }

    @Override
    public void updateFill(MetaObject metaObject) {
        // namespaceId 通常不在更新时变化，如有需要可在此处理
    }

    private boolean supportsTenantFill(MetaObject metaObject) {
        Object original = metaObject.getOriginalObject();
        if (original instanceof AbstractAutoGeneratedIdAuditableTenantable) {
            return true;
        }
        if (metaObject.hasGetter("et")) {
            Object et = metaObject.getValue("et");
            return et instanceof AbstractAutoGeneratedIdAuditableTenantable;
        }
        return false;
    }

    private String currentTenantId() {
        return tenantContextAware.getCurrentTenantId()
                .orElseThrow(() -> new IllegalStateException("缺少租户上下文，无法填充 namespaceId"));
    }
}


